#ifndef SSD_DISPLAYDATAMACROS_H
#define SSD_DISPLAYDATAMACROS_H

#define SSD_DISPLAY_DATA_WIDTH SSD_Hardware::displayData.getWidth()
#define SSD_DISPLAY_DATA_HEIGHT SSD_Hardware::displayData.getHeight()
#define SSD_DISPLAY_DATA_LINE_DELAY SSD_Hardware::displayData.getLineDelay()
#define SSD_DISPLAY_DATA_FILL_DELAY SSD_Hardware::displayData.getFillDelay()
#define SSD_DISPLAY_DATA_MIN_DELAY SSD_Hardware::displayData.getMinDelay()
#define SSD_DISPLAY_DATA_HAS_COM_SPLIT SSD_Hardware::displayData.hasComSplit()
#define SSD_DISPLAY_DATA_COLOR_DEPTH SSD_Hardware::displayData.getColorDepth()
#define SSD_DISPLAY_DATA_COLOR_ORDER SSD_Hardware::displayData.getColorOrder()
#define SSD_DISPLAY_DATA_GRAY_TABLE SSD_Hardware::displayData.getCustomGrayTable()
#define SSD_DISPLAY_DATA_CONTRAST_A SSD_Hardware::displayData.getContrastA()
#define SSD_DISPLAY_DATA_CONTRAST_B SSD_Hardware::displayData.getContrastB()
#define SSD_DISPLAY_DATA_CONTRAST_C SSD_Hardware::displayData.getContrastC()
#define SSD_DISPLAY_DATA_DEFAULT_BRIGHTNESS SSD_Hardware::displayData.getDefaultBrightness()
#define SSD_DISPLAY_DATA_PRECHARGE_PERIOD SSD_Hardware::displayData.getPreChargePeriod()
#define SSD_DISPLAY_DATA_PRECHARGE_SPEED_A SSD_Hardware::displayData.getPreChargeSpeedA()
#define SSD_DISPLAY_DATA_PRECHARGE_SPEED_B SSD_Hardware::displayData.getPreChargeSpeedB()
#define SSD_DISPLAY_DATA_PRECHARGE_SPEED_C SSD_Hardware::displayData.getPreChargeSpeedC()
#define SSD_DISPLAY_DATA_PRECHARGE_LEVEL SSD_Hardware::displayData.getPreChargeLevel()
#define SSD_DISPLAY_DATA_PRECHARGE_LEVEL_A SSD_Hardware::displayData.getPreChargeLevelA()
#define SSD_DISPLAY_DATA_PRECHARGE_LEVEL_B SSD_Hardware::displayData.getPreChargeLevelB()
#define SSD_DISPLAY_DATA_PRECHARGE_LEVEL_C SSD_Hardware::displayData.getPreChargeLevelC()
#define SSD_DISPLAY_DATA_START_LINE SSD_Hardware::displayData.getStartLine()
#define SSD_DISPLAY_DATA_OFFSET SSD_Hardware::displayData.getDisplayOffset()
#define SSD_DISPLAY_DATA_MUX_RATIO SSD_Hardware::displayData.getMuxRatio()
#define SSD_DISPLAY_DATA_MASTER_CONFIG SSD_Hardware::displayData.getMasterConfig()
#define SSD_DISPLAY_DATA_DIM_LEVEL_A SSD_Hardware::displayData.getDimLevelA()
#define SSD_DISPLAY_DATA_DIM_LEVEL_B SSD_Hardware::displayData.getDimLevelB()
#define SSD_DISPLAY_DATA_DIM_LEVEL_C SSD_Hardware::displayData.getDimLevelC()
#define SSD_DISPLAY_DATA_DIM_MODE_PRECHARGE SSD_Hardware::displayData.getDimModePreCharge()
#define SSD_DISPLAY_DATA_PHASE_PERIOD SSD_Hardware::displayData.getPhasePeriod()
#define SSD_DISPLAY_DATA_CLOCK_DIV SSD_Hardware::displayData.getClockDiv()
#define SSD_DISPLAY_DATA_VCOMH SSD_Hardware::displayData.getVComH()
#define SSD_DISPLAY_DATA_VSL_A SSD_Hardware::displayData.getVSLA()
#define SSD_DISPLAY_DATA_VSL_B SSD_Hardware::displayData.getVSLB()
#define SSD_DISPLAY_DATA_VSL_C SSD_Hardware::displayData.getVSLC()
#define SSD_DISPLAY_DATA_USE_ENHANCED_DISPLAY SSD_Hardware::displayData.useEnhancedDisplay()

#endif
